# Tencent is pleased to support the open source community by making 
# PhxPaxos available.
# Copyright (C) 2016 THL A29 Limited, a Tencent company. 
# All rights reserved.
# 
# Licensed under the BSD 3-Clause License (the "License"); you may 
# not use this file except in compliance with the License. You may 
# obtain a copy of the License at
# 
# https://opensource.org/licenses/BSD-3-Clause
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
# implied. See the License for the specific language governing 
# permissions and limitations under the License.
# 
# See the AUTHORS file for names of contributors. 

allobject=phx_paxos_test 

PHX_PAXOS_TEST_OBJ=test_sm.o test_server.o test_main.o

PHX_PAXOS_TEST_LIB=src/utils:utils src/comm:comm

PHX_PAXOS_TEST_SYS_LIB=$(PHXPAXOS_LIB_PATH)/libphxpaxos.a $(LEVELDB_LIB_PATH)/libleveldb.a $(PROTOBUF_LIB_PATH)/libprotobuf.a -lpthread

PHX_PAXOS_TEST_INCS=$(SRC_BASE_PATH)/src/test  $(PHXPAXOS_INCLUDE_PATH) $(LEVELDB_INCLUDE_PATH) $(PROTOBUF_INCLUDE_PATH) 

PHX_PAXOS_TEST_EXTRA_CPPFLAGS=-Wall -Werror

