image: Visual Studio 2017

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

before_build:
  - cmd: gyp_build.bat

platform: x86
configuration: Release
build:
  project: phxpaxos.sln
  verbosity: minimal