// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paxos_msg.proto

#ifndef PROTOBUF_paxos_5fmsg_2eproto__INCLUDED
#define PROTOBUF_paxos_5fmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace phxpaxos {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_paxos_5fmsg_2eproto();
void protobuf_AssignDesc_paxos_5fmsg_2eproto();
void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

class AcceptorStateData;
class CheckpointMsg;
class Header;
class MasterVariables;
class PaxosMsg;
class PaxosNodeInfo;
class SystemVariables;

// ===================================================================

class Header : public ::google::protobuf::Message {
 public:
  Header();
  virtual ~Header();

  Header(const Header& from);

  inline Header& operator=(const Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Header& default_instance();

  void Swap(Header* other);

  // implements Message ----------------------------------------------

  inline Header* New() const { return New(NULL); }

  Header* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Header& from);
  void MergeFrom(const Header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 gid = 1;
  bool has_gid() const;
  void clear_gid();
  static const int kGidFieldNumber = 1;
  ::google::protobuf::uint64 gid() const;
  void set_gid(::google::protobuf::uint64 value);

  // required uint64 rid = 2;
  bool has_rid() const;
  void clear_rid();
  static const int kRidFieldNumber = 2;
  ::google::protobuf::uint64 rid() const;
  void set_rid(::google::protobuf::uint64 value);

  // required int32 cmdid = 3;
  bool has_cmdid() const;
  void clear_cmdid();
  static const int kCmdidFieldNumber = 3;
  ::google::protobuf::int32 cmdid() const;
  void set_cmdid(::google::protobuf::int32 value);

  // optional int32 version = 4;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 4;
  ::google::protobuf::int32 version() const;
  void set_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:phxpaxos.Header)
 private:
  inline void set_has_gid();
  inline void clear_has_gid();
  inline void set_has_rid();
  inline void clear_has_rid();
  inline void set_has_cmdid();
  inline void clear_has_cmdid();
  inline void set_has_version();
  inline void clear_has_version();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 gid_;
  ::google::protobuf::uint64 rid_;
  ::google::protobuf::int32 cmdid_;
  ::google::protobuf::int32 version_;
  friend void  protobuf_AddDesc_paxos_5fmsg_2eproto();
  friend void protobuf_AssignDesc_paxos_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static Header* default_instance_;
};
// -------------------------------------------------------------------

class PaxosMsg : public ::google::protobuf::Message {
 public:
  PaxosMsg();
  virtual ~PaxosMsg();

  PaxosMsg(const PaxosMsg& from);

  inline PaxosMsg& operator=(const PaxosMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PaxosMsg& default_instance();

  void Swap(PaxosMsg* other);

  // implements Message ----------------------------------------------

  inline PaxosMsg* New() const { return New(NULL); }

  PaxosMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PaxosMsg& from);
  void MergeFrom(const PaxosMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PaxosMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 MsgType = 1;
  bool has_msgtype() const;
  void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  ::google::protobuf::int32 msgtype() const;
  void set_msgtype(::google::protobuf::int32 value);

  // optional uint64 InstanceID = 2;
  bool has_instanceid() const;
  void clear_instanceid();
  static const int kInstanceIDFieldNumber = 2;
  ::google::protobuf::uint64 instanceid() const;
  void set_instanceid(::google::protobuf::uint64 value);

  // optional uint64 NodeID = 3;
  bool has_nodeid() const;
  void clear_nodeid();
  static const int kNodeIDFieldNumber = 3;
  ::google::protobuf::uint64 nodeid() const;
  void set_nodeid(::google::protobuf::uint64 value);

  // optional uint64 ProposalID = 4;
  bool has_proposalid() const;
  void clear_proposalid();
  static const int kProposalIDFieldNumber = 4;
  ::google::protobuf::uint64 proposalid() const;
  void set_proposalid(::google::protobuf::uint64 value);

  // optional uint64 ProposalNodeID = 5;
  bool has_proposalnodeid() const;
  void clear_proposalnodeid();
  static const int kProposalNodeIDFieldNumber = 5;
  ::google::protobuf::uint64 proposalnodeid() const;
  void set_proposalnodeid(::google::protobuf::uint64 value);

  // optional bytes Value = 6;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 6;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // optional uint64 PreAcceptID = 7;
  bool has_preacceptid() const;
  void clear_preacceptid();
  static const int kPreAcceptIDFieldNumber = 7;
  ::google::protobuf::uint64 preacceptid() const;
  void set_preacceptid(::google::protobuf::uint64 value);

  // optional uint64 PreAcceptNodeID = 8;
  bool has_preacceptnodeid() const;
  void clear_preacceptnodeid();
  static const int kPreAcceptNodeIDFieldNumber = 8;
  ::google::protobuf::uint64 preacceptnodeid() const;
  void set_preacceptnodeid(::google::protobuf::uint64 value);

  // optional uint64 RejectByPromiseID = 9;
  bool has_rejectbypromiseid() const;
  void clear_rejectbypromiseid();
  static const int kRejectByPromiseIDFieldNumber = 9;
  ::google::protobuf::uint64 rejectbypromiseid() const;
  void set_rejectbypromiseid(::google::protobuf::uint64 value);

  // optional uint64 NowInstanceID = 10;
  bool has_nowinstanceid() const;
  void clear_nowinstanceid();
  static const int kNowInstanceIDFieldNumber = 10;
  ::google::protobuf::uint64 nowinstanceid() const;
  void set_nowinstanceid(::google::protobuf::uint64 value);

  // optional uint64 MinChosenInstanceID = 11;
  bool has_minchoseninstanceid() const;
  void clear_minchoseninstanceid();
  static const int kMinChosenInstanceIDFieldNumber = 11;
  ::google::protobuf::uint64 minchoseninstanceid() const;
  void set_minchoseninstanceid(::google::protobuf::uint64 value);

  // optional uint32 LastChecksum = 12;
  bool has_lastchecksum() const;
  void clear_lastchecksum();
  static const int kLastChecksumFieldNumber = 12;
  ::google::protobuf::uint32 lastchecksum() const;
  void set_lastchecksum(::google::protobuf::uint32 value);

  // optional uint32 Flag = 13;
  bool has_flag() const;
  void clear_flag();
  static const int kFlagFieldNumber = 13;
  ::google::protobuf::uint32 flag() const;
  void set_flag(::google::protobuf::uint32 value);

  // optional bytes SystemVariables = 14;
  bool has_systemvariables() const;
  void clear_systemvariables();
  static const int kSystemVariablesFieldNumber = 14;
  const ::std::string& systemvariables() const;
  void set_systemvariables(const ::std::string& value);
  void set_systemvariables(const char* value);
  void set_systemvariables(const void* value, size_t size);
  ::std::string* mutable_systemvariables();
  ::std::string* release_systemvariables();
  void set_allocated_systemvariables(::std::string* systemvariables);

  // optional bytes MasterVariables = 15;
  bool has_mastervariables() const;
  void clear_mastervariables();
  static const int kMasterVariablesFieldNumber = 15;
  const ::std::string& mastervariables() const;
  void set_mastervariables(const ::std::string& value);
  void set_mastervariables(const char* value);
  void set_mastervariables(const void* value, size_t size);
  ::std::string* mutable_mastervariables();
  ::std::string* release_mastervariables();
  void set_allocated_mastervariables(::std::string* mastervariables);

  // @@protoc_insertion_point(class_scope:phxpaxos.PaxosMsg)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_instanceid();
  inline void clear_has_instanceid();
  inline void set_has_nodeid();
  inline void clear_has_nodeid();
  inline void set_has_proposalid();
  inline void clear_has_proposalid();
  inline void set_has_proposalnodeid();
  inline void clear_has_proposalnodeid();
  inline void set_has_value();
  inline void clear_has_value();
  inline void set_has_preacceptid();
  inline void clear_has_preacceptid();
  inline void set_has_preacceptnodeid();
  inline void clear_has_preacceptnodeid();
  inline void set_has_rejectbypromiseid();
  inline void clear_has_rejectbypromiseid();
  inline void set_has_nowinstanceid();
  inline void clear_has_nowinstanceid();
  inline void set_has_minchoseninstanceid();
  inline void clear_has_minchoseninstanceid();
  inline void set_has_lastchecksum();
  inline void clear_has_lastchecksum();
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_systemvariables();
  inline void clear_has_systemvariables();
  inline void set_has_mastervariables();
  inline void clear_has_mastervariables();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 instanceid_;
  ::google::protobuf::uint64 nodeid_;
  ::google::protobuf::uint64 proposalid_;
  ::google::protobuf::uint64 proposalnodeid_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::int32 msgtype_;
  ::google::protobuf::uint32 lastchecksum_;
  ::google::protobuf::uint64 preacceptid_;
  ::google::protobuf::uint64 preacceptnodeid_;
  ::google::protobuf::uint64 rejectbypromiseid_;
  ::google::protobuf::uint64 nowinstanceid_;
  ::google::protobuf::uint64 minchoseninstanceid_;
  ::google::protobuf::internal::ArenaStringPtr systemvariables_;
  ::google::protobuf::internal::ArenaStringPtr mastervariables_;
  ::google::protobuf::uint32 flag_;
  friend void  protobuf_AddDesc_paxos_5fmsg_2eproto();
  friend void protobuf_AssignDesc_paxos_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static PaxosMsg* default_instance_;
};
// -------------------------------------------------------------------

class CheckpointMsg : public ::google::protobuf::Message {
 public:
  CheckpointMsg();
  virtual ~CheckpointMsg();

  CheckpointMsg(const CheckpointMsg& from);

  inline CheckpointMsg& operator=(const CheckpointMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CheckpointMsg& default_instance();

  void Swap(CheckpointMsg* other);

  // implements Message ----------------------------------------------

  inline CheckpointMsg* New() const { return New(NULL); }

  CheckpointMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CheckpointMsg& from);
  void MergeFrom(const CheckpointMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CheckpointMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 MsgType = 1;
  bool has_msgtype() const;
  void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  ::google::protobuf::int32 msgtype() const;
  void set_msgtype(::google::protobuf::int32 value);

  // required uint64 NodeID = 2;
  bool has_nodeid() const;
  void clear_nodeid();
  static const int kNodeIDFieldNumber = 2;
  ::google::protobuf::uint64 nodeid() const;
  void set_nodeid(::google::protobuf::uint64 value);

  // optional int32 Flag = 3;
  bool has_flag() const;
  void clear_flag();
  static const int kFlagFieldNumber = 3;
  ::google::protobuf::int32 flag() const;
  void set_flag(::google::protobuf::int32 value);

  // required uint64 UUID = 4;
  bool has_uuid() const;
  void clear_uuid();
  static const int kUUIDFieldNumber = 4;
  ::google::protobuf::uint64 uuid() const;
  void set_uuid(::google::protobuf::uint64 value);

  // required uint64 Sequence = 5;
  bool has_sequence() const;
  void clear_sequence();
  static const int kSequenceFieldNumber = 5;
  ::google::protobuf::uint64 sequence() const;
  void set_sequence(::google::protobuf::uint64 value);

  // optional uint64 CheckpointInstanceID = 6;
  bool has_checkpointinstanceid() const;
  void clear_checkpointinstanceid();
  static const int kCheckpointInstanceIDFieldNumber = 6;
  ::google::protobuf::uint64 checkpointinstanceid() const;
  void set_checkpointinstanceid(::google::protobuf::uint64 value);

  // optional uint32 Checksum = 7;
  bool has_checksum() const;
  void clear_checksum();
  static const int kChecksumFieldNumber = 7;
  ::google::protobuf::uint32 checksum() const;
  void set_checksum(::google::protobuf::uint32 value);

  // optional string FilePath = 8;
  bool has_filepath() const;
  void clear_filepath();
  static const int kFilePathFieldNumber = 8;
  const ::std::string& filepath() const;
  void set_filepath(const ::std::string& value);
  void set_filepath(const char* value);
  void set_filepath(const char* value, size_t size);
  ::std::string* mutable_filepath();
  ::std::string* release_filepath();
  void set_allocated_filepath(::std::string* filepath);

  // optional int32 SMID = 9;
  bool has_smid() const;
  void clear_smid();
  static const int kSMIDFieldNumber = 9;
  ::google::protobuf::int32 smid() const;
  void set_smid(::google::protobuf::int32 value);

  // optional uint64 Offset = 10;
  bool has_offset() const;
  void clear_offset();
  static const int kOffsetFieldNumber = 10;
  ::google::protobuf::uint64 offset() const;
  void set_offset(::google::protobuf::uint64 value);

  // optional bytes Buffer = 11;
  bool has_buffer() const;
  void clear_buffer();
  static const int kBufferFieldNumber = 11;
  const ::std::string& buffer() const;
  void set_buffer(const ::std::string& value);
  void set_buffer(const char* value);
  void set_buffer(const void* value, size_t size);
  ::std::string* mutable_buffer();
  ::std::string* release_buffer();
  void set_allocated_buffer(::std::string* buffer);

  // @@protoc_insertion_point(class_scope:phxpaxos.CheckpointMsg)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_nodeid();
  inline void clear_has_nodeid();
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_uuid();
  inline void clear_has_uuid();
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_checkpointinstanceid();
  inline void clear_has_checkpointinstanceid();
  inline void set_has_checksum();
  inline void clear_has_checksum();
  inline void set_has_filepath();
  inline void clear_has_filepath();
  inline void set_has_smid();
  inline void clear_has_smid();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_buffer();
  inline void clear_has_buffer();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 nodeid_;
  ::google::protobuf::int32 msgtype_;
  ::google::protobuf::int32 flag_;
  ::google::protobuf::uint64 uuid_;
  ::google::protobuf::uint64 sequence_;
  ::google::protobuf::uint64 checkpointinstanceid_;
  ::google::protobuf::internal::ArenaStringPtr filepath_;
  ::google::protobuf::uint32 checksum_;
  ::google::protobuf::int32 smid_;
  ::google::protobuf::uint64 offset_;
  ::google::protobuf::internal::ArenaStringPtr buffer_;
  friend void  protobuf_AddDesc_paxos_5fmsg_2eproto();
  friend void protobuf_AssignDesc_paxos_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static CheckpointMsg* default_instance_;
};
// -------------------------------------------------------------------

class AcceptorStateData : public ::google::protobuf::Message {
 public:
  AcceptorStateData();
  virtual ~AcceptorStateData();

  AcceptorStateData(const AcceptorStateData& from);

  inline AcceptorStateData& operator=(const AcceptorStateData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AcceptorStateData& default_instance();

  void Swap(AcceptorStateData* other);

  // implements Message ----------------------------------------------

  inline AcceptorStateData* New() const { return New(NULL); }

  AcceptorStateData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AcceptorStateData& from);
  void MergeFrom(const AcceptorStateData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AcceptorStateData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 InstanceID = 1;
  bool has_instanceid() const;
  void clear_instanceid();
  static const int kInstanceIDFieldNumber = 1;
  ::google::protobuf::uint64 instanceid() const;
  void set_instanceid(::google::protobuf::uint64 value);

  // required uint64 PromiseID = 2;
  bool has_promiseid() const;
  void clear_promiseid();
  static const int kPromiseIDFieldNumber = 2;
  ::google::protobuf::uint64 promiseid() const;
  void set_promiseid(::google::protobuf::uint64 value);

  // required uint64 PromiseNodeID = 3;
  bool has_promisenodeid() const;
  void clear_promisenodeid();
  static const int kPromiseNodeIDFieldNumber = 3;
  ::google::protobuf::uint64 promisenodeid() const;
  void set_promisenodeid(::google::protobuf::uint64 value);

  // required uint64 AcceptedID = 4;
  bool has_acceptedid() const;
  void clear_acceptedid();
  static const int kAcceptedIDFieldNumber = 4;
  ::google::protobuf::uint64 acceptedid() const;
  void set_acceptedid(::google::protobuf::uint64 value);

  // required uint64 AcceptedNodeID = 5;
  bool has_acceptednodeid() const;
  void clear_acceptednodeid();
  static const int kAcceptedNodeIDFieldNumber = 5;
  ::google::protobuf::uint64 acceptednodeid() const;
  void set_acceptednodeid(::google::protobuf::uint64 value);

  // required bytes AcceptedValue = 6;
  bool has_acceptedvalue() const;
  void clear_acceptedvalue();
  static const int kAcceptedValueFieldNumber = 6;
  const ::std::string& acceptedvalue() const;
  void set_acceptedvalue(const ::std::string& value);
  void set_acceptedvalue(const char* value);
  void set_acceptedvalue(const void* value, size_t size);
  ::std::string* mutable_acceptedvalue();
  ::std::string* release_acceptedvalue();
  void set_allocated_acceptedvalue(::std::string* acceptedvalue);

  // required uint32 Checksum = 7;
  bool has_checksum() const;
  void clear_checksum();
  static const int kChecksumFieldNumber = 7;
  ::google::protobuf::uint32 checksum() const;
  void set_checksum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:phxpaxos.AcceptorStateData)
 private:
  inline void set_has_instanceid();
  inline void clear_has_instanceid();
  inline void set_has_promiseid();
  inline void clear_has_promiseid();
  inline void set_has_promisenodeid();
  inline void clear_has_promisenodeid();
  inline void set_has_acceptedid();
  inline void clear_has_acceptedid();
  inline void set_has_acceptednodeid();
  inline void clear_has_acceptednodeid();
  inline void set_has_acceptedvalue();
  inline void clear_has_acceptedvalue();
  inline void set_has_checksum();
  inline void clear_has_checksum();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 instanceid_;
  ::google::protobuf::uint64 promiseid_;
  ::google::protobuf::uint64 promisenodeid_;
  ::google::protobuf::uint64 acceptedid_;
  ::google::protobuf::uint64 acceptednodeid_;
  ::google::protobuf::internal::ArenaStringPtr acceptedvalue_;
  ::google::protobuf::uint32 checksum_;
  friend void  protobuf_AddDesc_paxos_5fmsg_2eproto();
  friend void protobuf_AssignDesc_paxos_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static AcceptorStateData* default_instance_;
};
// -------------------------------------------------------------------

class PaxosNodeInfo : public ::google::protobuf::Message {
 public:
  PaxosNodeInfo();
  virtual ~PaxosNodeInfo();

  PaxosNodeInfo(const PaxosNodeInfo& from);

  inline PaxosNodeInfo& operator=(const PaxosNodeInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PaxosNodeInfo& default_instance();

  void Swap(PaxosNodeInfo* other);

  // implements Message ----------------------------------------------

  inline PaxosNodeInfo* New() const { return New(NULL); }

  PaxosNodeInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PaxosNodeInfo& from);
  void MergeFrom(const PaxosNodeInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PaxosNodeInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 Rid = 1;
  bool has_rid() const;
  void clear_rid();
  static const int kRidFieldNumber = 1;
  ::google::protobuf::uint64 rid() const;
  void set_rid(::google::protobuf::uint64 value);

  // required uint64 Nodeid = 2;
  bool has_nodeid() const;
  void clear_nodeid();
  static const int kNodeidFieldNumber = 2;
  ::google::protobuf::uint64 nodeid() const;
  void set_nodeid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:phxpaxos.PaxosNodeInfo)
 private:
  inline void set_has_rid();
  inline void clear_has_rid();
  inline void set_has_nodeid();
  inline void clear_has_nodeid();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 rid_;
  ::google::protobuf::uint64 nodeid_;
  friend void  protobuf_AddDesc_paxos_5fmsg_2eproto();
  friend void protobuf_AssignDesc_paxos_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static PaxosNodeInfo* default_instance_;
};
// -------------------------------------------------------------------

class SystemVariables : public ::google::protobuf::Message {
 public:
  SystemVariables();
  virtual ~SystemVariables();

  SystemVariables(const SystemVariables& from);

  inline SystemVariables& operator=(const SystemVariables& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SystemVariables& default_instance();

  void Swap(SystemVariables* other);

  // implements Message ----------------------------------------------

  inline SystemVariables* New() const { return New(NULL); }

  SystemVariables* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SystemVariables& from);
  void MergeFrom(const SystemVariables& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SystemVariables* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 Gid = 1;
  bool has_gid() const;
  void clear_gid();
  static const int kGidFieldNumber = 1;
  ::google::protobuf::uint64 gid() const;
  void set_gid(::google::protobuf::uint64 value);

  // repeated .phxpaxos.PaxosNodeInfo MemberShip = 2;
  int membership_size() const;
  void clear_membership();
  static const int kMemberShipFieldNumber = 2;
  const ::phxpaxos::PaxosNodeInfo& membership(int index) const;
  ::phxpaxos::PaxosNodeInfo* mutable_membership(int index);
  ::phxpaxos::PaxosNodeInfo* add_membership();
  ::google::protobuf::RepeatedPtrField< ::phxpaxos::PaxosNodeInfo >*
      mutable_membership();
  const ::google::protobuf::RepeatedPtrField< ::phxpaxos::PaxosNodeInfo >&
      membership() const;

  // required uint64 Version = 3;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 3;
  ::google::protobuf::uint64 version() const;
  void set_version(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:phxpaxos.SystemVariables)
 private:
  inline void set_has_gid();
  inline void clear_has_gid();
  inline void set_has_version();
  inline void clear_has_version();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 gid_;
  ::google::protobuf::RepeatedPtrField< ::phxpaxos::PaxosNodeInfo > membership_;
  ::google::protobuf::uint64 version_;
  friend void  protobuf_AddDesc_paxos_5fmsg_2eproto();
  friend void protobuf_AssignDesc_paxos_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static SystemVariables* default_instance_;
};
// -------------------------------------------------------------------

class MasterVariables : public ::google::protobuf::Message {
 public:
  MasterVariables();
  virtual ~MasterVariables();

  MasterVariables(const MasterVariables& from);

  inline MasterVariables& operator=(const MasterVariables& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MasterVariables& default_instance();

  void Swap(MasterVariables* other);

  // implements Message ----------------------------------------------

  inline MasterVariables* New() const { return New(NULL); }

  MasterVariables* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MasterVariables& from);
  void MergeFrom(const MasterVariables& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MasterVariables* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 MasterNodeid = 1;
  bool has_masternodeid() const;
  void clear_masternodeid();
  static const int kMasterNodeidFieldNumber = 1;
  ::google::protobuf::uint64 masternodeid() const;
  void set_masternodeid(::google::protobuf::uint64 value);

  // required uint64 Version = 2;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::uint64 version() const;
  void set_version(::google::protobuf::uint64 value);

  // required uint32 LeaseTime = 3;
  bool has_leasetime() const;
  void clear_leasetime();
  static const int kLeaseTimeFieldNumber = 3;
  ::google::protobuf::uint32 leasetime() const;
  void set_leasetime(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:phxpaxos.MasterVariables)
 private:
  inline void set_has_masternodeid();
  inline void clear_has_masternodeid();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_leasetime();
  inline void clear_has_leasetime();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 masternodeid_;
  ::google::protobuf::uint64 version_;
  ::google::protobuf::uint32 leasetime_;
  friend void  protobuf_AddDesc_paxos_5fmsg_2eproto();
  friend void protobuf_AssignDesc_paxos_5fmsg_2eproto();
  friend void protobuf_ShutdownFile_paxos_5fmsg_2eproto();

  void InitAsDefaultInstance();
  static MasterVariables* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Header

// required uint64 gid = 1;
inline bool Header::has_gid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Header::set_has_gid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Header::clear_has_gid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Header::clear_gid() {
  gid_ = GOOGLE_ULONGLONG(0);
  clear_has_gid();
}
inline ::google::protobuf::uint64 Header::gid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.Header.gid)
  return gid_;
}
inline void Header::set_gid(::google::protobuf::uint64 value) {
  set_has_gid();
  gid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.Header.gid)
}

// required uint64 rid = 2;
inline bool Header::has_rid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Header::set_has_rid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Header::clear_has_rid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Header::clear_rid() {
  rid_ = GOOGLE_ULONGLONG(0);
  clear_has_rid();
}
inline ::google::protobuf::uint64 Header::rid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.Header.rid)
  return rid_;
}
inline void Header::set_rid(::google::protobuf::uint64 value) {
  set_has_rid();
  rid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.Header.rid)
}

// required int32 cmdid = 3;
inline bool Header::has_cmdid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Header::set_has_cmdid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Header::clear_has_cmdid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Header::clear_cmdid() {
  cmdid_ = 0;
  clear_has_cmdid();
}
inline ::google::protobuf::int32 Header::cmdid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.Header.cmdid)
  return cmdid_;
}
inline void Header::set_cmdid(::google::protobuf::int32 value) {
  set_has_cmdid();
  cmdid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.Header.cmdid)
}

// optional int32 version = 4;
inline bool Header::has_version() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Header::set_has_version() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Header::clear_has_version() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Header::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::google::protobuf::int32 Header::version() const {
  // @@protoc_insertion_point(field_get:phxpaxos.Header.version)
  return version_;
}
inline void Header::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.Header.version)
}

// -------------------------------------------------------------------

// PaxosMsg

// required int32 MsgType = 1;
inline bool PaxosMsg::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PaxosMsg::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PaxosMsg::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PaxosMsg::clear_msgtype() {
  msgtype_ = 0;
  clear_has_msgtype();
}
inline ::google::protobuf::int32 PaxosMsg::msgtype() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.MsgType)
  return msgtype_;
}
inline void PaxosMsg::set_msgtype(::google::protobuf::int32 value) {
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.MsgType)
}

// optional uint64 InstanceID = 2;
inline bool PaxosMsg::has_instanceid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PaxosMsg::set_has_instanceid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PaxosMsg::clear_has_instanceid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PaxosMsg::clear_instanceid() {
  instanceid_ = GOOGLE_ULONGLONG(0);
  clear_has_instanceid();
}
inline ::google::protobuf::uint64 PaxosMsg::instanceid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.InstanceID)
  return instanceid_;
}
inline void PaxosMsg::set_instanceid(::google::protobuf::uint64 value) {
  set_has_instanceid();
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.InstanceID)
}

// optional uint64 NodeID = 3;
inline bool PaxosMsg::has_nodeid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PaxosMsg::set_has_nodeid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PaxosMsg::clear_has_nodeid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PaxosMsg::clear_nodeid() {
  nodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_nodeid();
}
inline ::google::protobuf::uint64 PaxosMsg::nodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.NodeID)
  return nodeid_;
}
inline void PaxosMsg::set_nodeid(::google::protobuf::uint64 value) {
  set_has_nodeid();
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.NodeID)
}

// optional uint64 ProposalID = 4;
inline bool PaxosMsg::has_proposalid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PaxosMsg::set_has_proposalid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PaxosMsg::clear_has_proposalid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PaxosMsg::clear_proposalid() {
  proposalid_ = GOOGLE_ULONGLONG(0);
  clear_has_proposalid();
}
inline ::google::protobuf::uint64 PaxosMsg::proposalid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.ProposalID)
  return proposalid_;
}
inline void PaxosMsg::set_proposalid(::google::protobuf::uint64 value) {
  set_has_proposalid();
  proposalid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.ProposalID)
}

// optional uint64 ProposalNodeID = 5;
inline bool PaxosMsg::has_proposalnodeid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PaxosMsg::set_has_proposalnodeid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PaxosMsg::clear_has_proposalnodeid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PaxosMsg::clear_proposalnodeid() {
  proposalnodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_proposalnodeid();
}
inline ::google::protobuf::uint64 PaxosMsg::proposalnodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.ProposalNodeID)
  return proposalnodeid_;
}
inline void PaxosMsg::set_proposalnodeid(::google::protobuf::uint64 value) {
  set_has_proposalnodeid();
  proposalnodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.ProposalNodeID)
}

// optional bytes Value = 6;
inline bool PaxosMsg::has_value() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PaxosMsg::set_has_value() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PaxosMsg::clear_has_value() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PaxosMsg::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& PaxosMsg::value() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.Value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaxosMsg::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.Value)
}
inline void PaxosMsg::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxpaxos.PaxosMsg.Value)
}
inline void PaxosMsg::set_value(const void* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxpaxos.PaxosMsg.Value)
}
inline ::std::string* PaxosMsg::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:phxpaxos.PaxosMsg.Value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaxosMsg::release_value() {
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaxosMsg::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:phxpaxos.PaxosMsg.Value)
}

// optional uint64 PreAcceptID = 7;
inline bool PaxosMsg::has_preacceptid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PaxosMsg::set_has_preacceptid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PaxosMsg::clear_has_preacceptid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PaxosMsg::clear_preacceptid() {
  preacceptid_ = GOOGLE_ULONGLONG(0);
  clear_has_preacceptid();
}
inline ::google::protobuf::uint64 PaxosMsg::preacceptid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.PreAcceptID)
  return preacceptid_;
}
inline void PaxosMsg::set_preacceptid(::google::protobuf::uint64 value) {
  set_has_preacceptid();
  preacceptid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.PreAcceptID)
}

// optional uint64 PreAcceptNodeID = 8;
inline bool PaxosMsg::has_preacceptnodeid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PaxosMsg::set_has_preacceptnodeid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PaxosMsg::clear_has_preacceptnodeid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PaxosMsg::clear_preacceptnodeid() {
  preacceptnodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_preacceptnodeid();
}
inline ::google::protobuf::uint64 PaxosMsg::preacceptnodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.PreAcceptNodeID)
  return preacceptnodeid_;
}
inline void PaxosMsg::set_preacceptnodeid(::google::protobuf::uint64 value) {
  set_has_preacceptnodeid();
  preacceptnodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.PreAcceptNodeID)
}

// optional uint64 RejectByPromiseID = 9;
inline bool PaxosMsg::has_rejectbypromiseid() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PaxosMsg::set_has_rejectbypromiseid() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PaxosMsg::clear_has_rejectbypromiseid() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PaxosMsg::clear_rejectbypromiseid() {
  rejectbypromiseid_ = GOOGLE_ULONGLONG(0);
  clear_has_rejectbypromiseid();
}
inline ::google::protobuf::uint64 PaxosMsg::rejectbypromiseid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.RejectByPromiseID)
  return rejectbypromiseid_;
}
inline void PaxosMsg::set_rejectbypromiseid(::google::protobuf::uint64 value) {
  set_has_rejectbypromiseid();
  rejectbypromiseid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.RejectByPromiseID)
}

// optional uint64 NowInstanceID = 10;
inline bool PaxosMsg::has_nowinstanceid() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void PaxosMsg::set_has_nowinstanceid() {
  _has_bits_[0] |= 0x00000200u;
}
inline void PaxosMsg::clear_has_nowinstanceid() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void PaxosMsg::clear_nowinstanceid() {
  nowinstanceid_ = GOOGLE_ULONGLONG(0);
  clear_has_nowinstanceid();
}
inline ::google::protobuf::uint64 PaxosMsg::nowinstanceid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.NowInstanceID)
  return nowinstanceid_;
}
inline void PaxosMsg::set_nowinstanceid(::google::protobuf::uint64 value) {
  set_has_nowinstanceid();
  nowinstanceid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.NowInstanceID)
}

// optional uint64 MinChosenInstanceID = 11;
inline bool PaxosMsg::has_minchoseninstanceid() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void PaxosMsg::set_has_minchoseninstanceid() {
  _has_bits_[0] |= 0x00000400u;
}
inline void PaxosMsg::clear_has_minchoseninstanceid() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void PaxosMsg::clear_minchoseninstanceid() {
  minchoseninstanceid_ = GOOGLE_ULONGLONG(0);
  clear_has_minchoseninstanceid();
}
inline ::google::protobuf::uint64 PaxosMsg::minchoseninstanceid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.MinChosenInstanceID)
  return minchoseninstanceid_;
}
inline void PaxosMsg::set_minchoseninstanceid(::google::protobuf::uint64 value) {
  set_has_minchoseninstanceid();
  minchoseninstanceid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.MinChosenInstanceID)
}

// optional uint32 LastChecksum = 12;
inline bool PaxosMsg::has_lastchecksum() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void PaxosMsg::set_has_lastchecksum() {
  _has_bits_[0] |= 0x00000800u;
}
inline void PaxosMsg::clear_has_lastchecksum() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void PaxosMsg::clear_lastchecksum() {
  lastchecksum_ = 0u;
  clear_has_lastchecksum();
}
inline ::google::protobuf::uint32 PaxosMsg::lastchecksum() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.LastChecksum)
  return lastchecksum_;
}
inline void PaxosMsg::set_lastchecksum(::google::protobuf::uint32 value) {
  set_has_lastchecksum();
  lastchecksum_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.LastChecksum)
}

// optional uint32 Flag = 13;
inline bool PaxosMsg::has_flag() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void PaxosMsg::set_has_flag() {
  _has_bits_[0] |= 0x00001000u;
}
inline void PaxosMsg::clear_has_flag() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void PaxosMsg::clear_flag() {
  flag_ = 0u;
  clear_has_flag();
}
inline ::google::protobuf::uint32 PaxosMsg::flag() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.Flag)
  return flag_;
}
inline void PaxosMsg::set_flag(::google::protobuf::uint32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.Flag)
}

// optional bytes SystemVariables = 14;
inline bool PaxosMsg::has_systemvariables() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void PaxosMsg::set_has_systemvariables() {
  _has_bits_[0] |= 0x00002000u;
}
inline void PaxosMsg::clear_has_systemvariables() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void PaxosMsg::clear_systemvariables() {
  systemvariables_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_systemvariables();
}
inline const ::std::string& PaxosMsg::systemvariables() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.SystemVariables)
  return systemvariables_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaxosMsg::set_systemvariables(const ::std::string& value) {
  set_has_systemvariables();
  systemvariables_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.SystemVariables)
}
inline void PaxosMsg::set_systemvariables(const char* value) {
  set_has_systemvariables();
  systemvariables_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxpaxos.PaxosMsg.SystemVariables)
}
inline void PaxosMsg::set_systemvariables(const void* value, size_t size) {
  set_has_systemvariables();
  systemvariables_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxpaxos.PaxosMsg.SystemVariables)
}
inline ::std::string* PaxosMsg::mutable_systemvariables() {
  set_has_systemvariables();
  // @@protoc_insertion_point(field_mutable:phxpaxos.PaxosMsg.SystemVariables)
  return systemvariables_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaxosMsg::release_systemvariables() {
  clear_has_systemvariables();
  return systemvariables_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaxosMsg::set_allocated_systemvariables(::std::string* systemvariables) {
  if (systemvariables != NULL) {
    set_has_systemvariables();
  } else {
    clear_has_systemvariables();
  }
  systemvariables_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), systemvariables);
  // @@protoc_insertion_point(field_set_allocated:phxpaxos.PaxosMsg.SystemVariables)
}

// optional bytes MasterVariables = 15;
inline bool PaxosMsg::has_mastervariables() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void PaxosMsg::set_has_mastervariables() {
  _has_bits_[0] |= 0x00004000u;
}
inline void PaxosMsg::clear_has_mastervariables() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void PaxosMsg::clear_mastervariables() {
  mastervariables_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_mastervariables();
}
inline const ::std::string& PaxosMsg::mastervariables() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosMsg.MasterVariables)
  return mastervariables_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaxosMsg::set_mastervariables(const ::std::string& value) {
  set_has_mastervariables();
  mastervariables_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosMsg.MasterVariables)
}
inline void PaxosMsg::set_mastervariables(const char* value) {
  set_has_mastervariables();
  mastervariables_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxpaxos.PaxosMsg.MasterVariables)
}
inline void PaxosMsg::set_mastervariables(const void* value, size_t size) {
  set_has_mastervariables();
  mastervariables_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxpaxos.PaxosMsg.MasterVariables)
}
inline ::std::string* PaxosMsg::mutable_mastervariables() {
  set_has_mastervariables();
  // @@protoc_insertion_point(field_mutable:phxpaxos.PaxosMsg.MasterVariables)
  return mastervariables_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaxosMsg::release_mastervariables() {
  clear_has_mastervariables();
  return mastervariables_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaxosMsg::set_allocated_mastervariables(::std::string* mastervariables) {
  if (mastervariables != NULL) {
    set_has_mastervariables();
  } else {
    clear_has_mastervariables();
  }
  mastervariables_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mastervariables);
  // @@protoc_insertion_point(field_set_allocated:phxpaxos.PaxosMsg.MasterVariables)
}

// -------------------------------------------------------------------

// CheckpointMsg

// required int32 MsgType = 1;
inline bool CheckpointMsg::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CheckpointMsg::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CheckpointMsg::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CheckpointMsg::clear_msgtype() {
  msgtype_ = 0;
  clear_has_msgtype();
}
inline ::google::protobuf::int32 CheckpointMsg::msgtype() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.MsgType)
  return msgtype_;
}
inline void CheckpointMsg::set_msgtype(::google::protobuf::int32 value) {
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.MsgType)
}

// required uint64 NodeID = 2;
inline bool CheckpointMsg::has_nodeid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CheckpointMsg::set_has_nodeid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CheckpointMsg::clear_has_nodeid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CheckpointMsg::clear_nodeid() {
  nodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_nodeid();
}
inline ::google::protobuf::uint64 CheckpointMsg::nodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.NodeID)
  return nodeid_;
}
inline void CheckpointMsg::set_nodeid(::google::protobuf::uint64 value) {
  set_has_nodeid();
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.NodeID)
}

// optional int32 Flag = 3;
inline bool CheckpointMsg::has_flag() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CheckpointMsg::set_has_flag() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CheckpointMsg::clear_has_flag() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CheckpointMsg::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 CheckpointMsg::flag() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.Flag)
  return flag_;
}
inline void CheckpointMsg::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.Flag)
}

// required uint64 UUID = 4;
inline bool CheckpointMsg::has_uuid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CheckpointMsg::set_has_uuid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CheckpointMsg::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CheckpointMsg::clear_uuid() {
  uuid_ = GOOGLE_ULONGLONG(0);
  clear_has_uuid();
}
inline ::google::protobuf::uint64 CheckpointMsg::uuid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.UUID)
  return uuid_;
}
inline void CheckpointMsg::set_uuid(::google::protobuf::uint64 value) {
  set_has_uuid();
  uuid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.UUID)
}

// required uint64 Sequence = 5;
inline bool CheckpointMsg::has_sequence() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CheckpointMsg::set_has_sequence() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CheckpointMsg::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CheckpointMsg::clear_sequence() {
  sequence_ = GOOGLE_ULONGLONG(0);
  clear_has_sequence();
}
inline ::google::protobuf::uint64 CheckpointMsg::sequence() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.Sequence)
  return sequence_;
}
inline void CheckpointMsg::set_sequence(::google::protobuf::uint64 value) {
  set_has_sequence();
  sequence_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.Sequence)
}

// optional uint64 CheckpointInstanceID = 6;
inline bool CheckpointMsg::has_checkpointinstanceid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CheckpointMsg::set_has_checkpointinstanceid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CheckpointMsg::clear_has_checkpointinstanceid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CheckpointMsg::clear_checkpointinstanceid() {
  checkpointinstanceid_ = GOOGLE_ULONGLONG(0);
  clear_has_checkpointinstanceid();
}
inline ::google::protobuf::uint64 CheckpointMsg::checkpointinstanceid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.CheckpointInstanceID)
  return checkpointinstanceid_;
}
inline void CheckpointMsg::set_checkpointinstanceid(::google::protobuf::uint64 value) {
  set_has_checkpointinstanceid();
  checkpointinstanceid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.CheckpointInstanceID)
}

// optional uint32 Checksum = 7;
inline bool CheckpointMsg::has_checksum() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CheckpointMsg::set_has_checksum() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CheckpointMsg::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CheckpointMsg::clear_checksum() {
  checksum_ = 0u;
  clear_has_checksum();
}
inline ::google::protobuf::uint32 CheckpointMsg::checksum() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.Checksum)
  return checksum_;
}
inline void CheckpointMsg::set_checksum(::google::protobuf::uint32 value) {
  set_has_checksum();
  checksum_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.Checksum)
}

// optional string FilePath = 8;
inline bool CheckpointMsg::has_filepath() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CheckpointMsg::set_has_filepath() {
  _has_bits_[0] |= 0x00000080u;
}
inline void CheckpointMsg::clear_has_filepath() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void CheckpointMsg::clear_filepath() {
  filepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_filepath();
}
inline const ::std::string& CheckpointMsg::filepath() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.FilePath)
  return filepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CheckpointMsg::set_filepath(const ::std::string& value) {
  set_has_filepath();
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.FilePath)
}
inline void CheckpointMsg::set_filepath(const char* value) {
  set_has_filepath();
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxpaxos.CheckpointMsg.FilePath)
}
inline void CheckpointMsg::set_filepath(const char* value, size_t size) {
  set_has_filepath();
  filepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxpaxos.CheckpointMsg.FilePath)
}
inline ::std::string* CheckpointMsg::mutable_filepath() {
  set_has_filepath();
  // @@protoc_insertion_point(field_mutable:phxpaxos.CheckpointMsg.FilePath)
  return filepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CheckpointMsg::release_filepath() {
  clear_has_filepath();
  return filepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CheckpointMsg::set_allocated_filepath(::std::string* filepath) {
  if (filepath != NULL) {
    set_has_filepath();
  } else {
    clear_has_filepath();
  }
  filepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filepath);
  // @@protoc_insertion_point(field_set_allocated:phxpaxos.CheckpointMsg.FilePath)
}

// optional int32 SMID = 9;
inline bool CheckpointMsg::has_smid() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void CheckpointMsg::set_has_smid() {
  _has_bits_[0] |= 0x00000100u;
}
inline void CheckpointMsg::clear_has_smid() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void CheckpointMsg::clear_smid() {
  smid_ = 0;
  clear_has_smid();
}
inline ::google::protobuf::int32 CheckpointMsg::smid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.SMID)
  return smid_;
}
inline void CheckpointMsg::set_smid(::google::protobuf::int32 value) {
  set_has_smid();
  smid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.SMID)
}

// optional uint64 Offset = 10;
inline bool CheckpointMsg::has_offset() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CheckpointMsg::set_has_offset() {
  _has_bits_[0] |= 0x00000200u;
}
inline void CheckpointMsg::clear_has_offset() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void CheckpointMsg::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::uint64 CheckpointMsg::offset() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.Offset)
  return offset_;
}
inline void CheckpointMsg::set_offset(::google::protobuf::uint64 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.Offset)
}

// optional bytes Buffer = 11;
inline bool CheckpointMsg::has_buffer() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void CheckpointMsg::set_has_buffer() {
  _has_bits_[0] |= 0x00000400u;
}
inline void CheckpointMsg::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void CheckpointMsg::clear_buffer() {
  buffer_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_buffer();
}
inline const ::std::string& CheckpointMsg::buffer() const {
  // @@protoc_insertion_point(field_get:phxpaxos.CheckpointMsg.Buffer)
  return buffer_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CheckpointMsg::set_buffer(const ::std::string& value) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxpaxos.CheckpointMsg.Buffer)
}
inline void CheckpointMsg::set_buffer(const char* value) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxpaxos.CheckpointMsg.Buffer)
}
inline void CheckpointMsg::set_buffer(const void* value, size_t size) {
  set_has_buffer();
  buffer_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxpaxos.CheckpointMsg.Buffer)
}
inline ::std::string* CheckpointMsg::mutable_buffer() {
  set_has_buffer();
  // @@protoc_insertion_point(field_mutable:phxpaxos.CheckpointMsg.Buffer)
  return buffer_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CheckpointMsg::release_buffer() {
  clear_has_buffer();
  return buffer_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CheckpointMsg::set_allocated_buffer(::std::string* buffer) {
  if (buffer != NULL) {
    set_has_buffer();
  } else {
    clear_has_buffer();
  }
  buffer_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buffer);
  // @@protoc_insertion_point(field_set_allocated:phxpaxos.CheckpointMsg.Buffer)
}

// -------------------------------------------------------------------

// AcceptorStateData

// required uint64 InstanceID = 1;
inline bool AcceptorStateData::has_instanceid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AcceptorStateData::set_has_instanceid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AcceptorStateData::clear_has_instanceid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AcceptorStateData::clear_instanceid() {
  instanceid_ = GOOGLE_ULONGLONG(0);
  clear_has_instanceid();
}
inline ::google::protobuf::uint64 AcceptorStateData::instanceid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.AcceptorStateData.InstanceID)
  return instanceid_;
}
inline void AcceptorStateData::set_instanceid(::google::protobuf::uint64 value) {
  set_has_instanceid();
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.AcceptorStateData.InstanceID)
}

// required uint64 PromiseID = 2;
inline bool AcceptorStateData::has_promiseid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AcceptorStateData::set_has_promiseid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AcceptorStateData::clear_has_promiseid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AcceptorStateData::clear_promiseid() {
  promiseid_ = GOOGLE_ULONGLONG(0);
  clear_has_promiseid();
}
inline ::google::protobuf::uint64 AcceptorStateData::promiseid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.AcceptorStateData.PromiseID)
  return promiseid_;
}
inline void AcceptorStateData::set_promiseid(::google::protobuf::uint64 value) {
  set_has_promiseid();
  promiseid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.AcceptorStateData.PromiseID)
}

// required uint64 PromiseNodeID = 3;
inline bool AcceptorStateData::has_promisenodeid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AcceptorStateData::set_has_promisenodeid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AcceptorStateData::clear_has_promisenodeid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AcceptorStateData::clear_promisenodeid() {
  promisenodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_promisenodeid();
}
inline ::google::protobuf::uint64 AcceptorStateData::promisenodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.AcceptorStateData.PromiseNodeID)
  return promisenodeid_;
}
inline void AcceptorStateData::set_promisenodeid(::google::protobuf::uint64 value) {
  set_has_promisenodeid();
  promisenodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.AcceptorStateData.PromiseNodeID)
}

// required uint64 AcceptedID = 4;
inline bool AcceptorStateData::has_acceptedid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AcceptorStateData::set_has_acceptedid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AcceptorStateData::clear_has_acceptedid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AcceptorStateData::clear_acceptedid() {
  acceptedid_ = GOOGLE_ULONGLONG(0);
  clear_has_acceptedid();
}
inline ::google::protobuf::uint64 AcceptorStateData::acceptedid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.AcceptorStateData.AcceptedID)
  return acceptedid_;
}
inline void AcceptorStateData::set_acceptedid(::google::protobuf::uint64 value) {
  set_has_acceptedid();
  acceptedid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.AcceptorStateData.AcceptedID)
}

// required uint64 AcceptedNodeID = 5;
inline bool AcceptorStateData::has_acceptednodeid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AcceptorStateData::set_has_acceptednodeid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AcceptorStateData::clear_has_acceptednodeid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AcceptorStateData::clear_acceptednodeid() {
  acceptednodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_acceptednodeid();
}
inline ::google::protobuf::uint64 AcceptorStateData::acceptednodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.AcceptorStateData.AcceptedNodeID)
  return acceptednodeid_;
}
inline void AcceptorStateData::set_acceptednodeid(::google::protobuf::uint64 value) {
  set_has_acceptednodeid();
  acceptednodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.AcceptorStateData.AcceptedNodeID)
}

// required bytes AcceptedValue = 6;
inline bool AcceptorStateData::has_acceptedvalue() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AcceptorStateData::set_has_acceptedvalue() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AcceptorStateData::clear_has_acceptedvalue() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AcceptorStateData::clear_acceptedvalue() {
  acceptedvalue_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_acceptedvalue();
}
inline const ::std::string& AcceptorStateData::acceptedvalue() const {
  // @@protoc_insertion_point(field_get:phxpaxos.AcceptorStateData.AcceptedValue)
  return acceptedvalue_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AcceptorStateData::set_acceptedvalue(const ::std::string& value) {
  set_has_acceptedvalue();
  acceptedvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxpaxos.AcceptorStateData.AcceptedValue)
}
inline void AcceptorStateData::set_acceptedvalue(const char* value) {
  set_has_acceptedvalue();
  acceptedvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxpaxos.AcceptorStateData.AcceptedValue)
}
inline void AcceptorStateData::set_acceptedvalue(const void* value, size_t size) {
  set_has_acceptedvalue();
  acceptedvalue_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxpaxos.AcceptorStateData.AcceptedValue)
}
inline ::std::string* AcceptorStateData::mutable_acceptedvalue() {
  set_has_acceptedvalue();
  // @@protoc_insertion_point(field_mutable:phxpaxos.AcceptorStateData.AcceptedValue)
  return acceptedvalue_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AcceptorStateData::release_acceptedvalue() {
  clear_has_acceptedvalue();
  return acceptedvalue_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AcceptorStateData::set_allocated_acceptedvalue(::std::string* acceptedvalue) {
  if (acceptedvalue != NULL) {
    set_has_acceptedvalue();
  } else {
    clear_has_acceptedvalue();
  }
  acceptedvalue_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), acceptedvalue);
  // @@protoc_insertion_point(field_set_allocated:phxpaxos.AcceptorStateData.AcceptedValue)
}

// required uint32 Checksum = 7;
inline bool AcceptorStateData::has_checksum() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void AcceptorStateData::set_has_checksum() {
  _has_bits_[0] |= 0x00000040u;
}
inline void AcceptorStateData::clear_has_checksum() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void AcceptorStateData::clear_checksum() {
  checksum_ = 0u;
  clear_has_checksum();
}
inline ::google::protobuf::uint32 AcceptorStateData::checksum() const {
  // @@protoc_insertion_point(field_get:phxpaxos.AcceptorStateData.Checksum)
  return checksum_;
}
inline void AcceptorStateData::set_checksum(::google::protobuf::uint32 value) {
  set_has_checksum();
  checksum_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.AcceptorStateData.Checksum)
}

// -------------------------------------------------------------------

// PaxosNodeInfo

// required uint64 Rid = 1;
inline bool PaxosNodeInfo::has_rid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PaxosNodeInfo::set_has_rid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PaxosNodeInfo::clear_has_rid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PaxosNodeInfo::clear_rid() {
  rid_ = GOOGLE_ULONGLONG(0);
  clear_has_rid();
}
inline ::google::protobuf::uint64 PaxosNodeInfo::rid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosNodeInfo.Rid)
  return rid_;
}
inline void PaxosNodeInfo::set_rid(::google::protobuf::uint64 value) {
  set_has_rid();
  rid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosNodeInfo.Rid)
}

// required uint64 Nodeid = 2;
inline bool PaxosNodeInfo::has_nodeid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PaxosNodeInfo::set_has_nodeid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PaxosNodeInfo::clear_has_nodeid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PaxosNodeInfo::clear_nodeid() {
  nodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_nodeid();
}
inline ::google::protobuf::uint64 PaxosNodeInfo::nodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.PaxosNodeInfo.Nodeid)
  return nodeid_;
}
inline void PaxosNodeInfo::set_nodeid(::google::protobuf::uint64 value) {
  set_has_nodeid();
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.PaxosNodeInfo.Nodeid)
}

// -------------------------------------------------------------------

// SystemVariables

// required uint64 Gid = 1;
inline bool SystemVariables::has_gid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemVariables::set_has_gid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemVariables::clear_has_gid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemVariables::clear_gid() {
  gid_ = GOOGLE_ULONGLONG(0);
  clear_has_gid();
}
inline ::google::protobuf::uint64 SystemVariables::gid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.SystemVariables.Gid)
  return gid_;
}
inline void SystemVariables::set_gid(::google::protobuf::uint64 value) {
  set_has_gid();
  gid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.SystemVariables.Gid)
}

// repeated .phxpaxos.PaxosNodeInfo MemberShip = 2;
inline int SystemVariables::membership_size() const {
  return membership_.size();
}
inline void SystemVariables::clear_membership() {
  membership_.Clear();
}
inline const ::phxpaxos::PaxosNodeInfo& SystemVariables::membership(int index) const {
  // @@protoc_insertion_point(field_get:phxpaxos.SystemVariables.MemberShip)
  return membership_.Get(index);
}
inline ::phxpaxos::PaxosNodeInfo* SystemVariables::mutable_membership(int index) {
  // @@protoc_insertion_point(field_mutable:phxpaxos.SystemVariables.MemberShip)
  return membership_.Mutable(index);
}
inline ::phxpaxos::PaxosNodeInfo* SystemVariables::add_membership() {
  // @@protoc_insertion_point(field_add:phxpaxos.SystemVariables.MemberShip)
  return membership_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::phxpaxos::PaxosNodeInfo >*
SystemVariables::mutable_membership() {
  // @@protoc_insertion_point(field_mutable_list:phxpaxos.SystemVariables.MemberShip)
  return &membership_;
}
inline const ::google::protobuf::RepeatedPtrField< ::phxpaxos::PaxosNodeInfo >&
SystemVariables::membership() const {
  // @@protoc_insertion_point(field_list:phxpaxos.SystemVariables.MemberShip)
  return membership_;
}

// required uint64 Version = 3;
inline bool SystemVariables::has_version() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SystemVariables::set_has_version() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SystemVariables::clear_has_version() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SystemVariables::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
  clear_has_version();
}
inline ::google::protobuf::uint64 SystemVariables::version() const {
  // @@protoc_insertion_point(field_get:phxpaxos.SystemVariables.Version)
  return version_;
}
inline void SystemVariables::set_version(::google::protobuf::uint64 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.SystemVariables.Version)
}

// -------------------------------------------------------------------

// MasterVariables

// required uint64 MasterNodeid = 1;
inline bool MasterVariables::has_masternodeid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MasterVariables::set_has_masternodeid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MasterVariables::clear_has_masternodeid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MasterVariables::clear_masternodeid() {
  masternodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_masternodeid();
}
inline ::google::protobuf::uint64 MasterVariables::masternodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterVariables.MasterNodeid)
  return masternodeid_;
}
inline void MasterVariables::set_masternodeid(::google::protobuf::uint64 value) {
  set_has_masternodeid();
  masternodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterVariables.MasterNodeid)
}

// required uint64 Version = 2;
inline bool MasterVariables::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MasterVariables::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MasterVariables::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MasterVariables::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
  clear_has_version();
}
inline ::google::protobuf::uint64 MasterVariables::version() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterVariables.Version)
  return version_;
}
inline void MasterVariables::set_version(::google::protobuf::uint64 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterVariables.Version)
}

// required uint32 LeaseTime = 3;
inline bool MasterVariables::has_leasetime() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MasterVariables::set_has_leasetime() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MasterVariables::clear_has_leasetime() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MasterVariables::clear_leasetime() {
  leasetime_ = 0u;
  clear_has_leasetime();
}
inline ::google::protobuf::uint32 MasterVariables::leasetime() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterVariables.LeaseTime)
  return leasetime_;
}
inline void MasterVariables::set_leasetime(::google::protobuf::uint32 value) {
  set_has_leasetime();
  leasetime_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterVariables.LeaseTime)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace phxpaxos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_paxos_5fmsg_2eproto__INCLUDED
