// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phxkv.proto

#ifndef PROTOBUF_phxkv_2eproto__INCLUDED
#define PROTOBUF_phxkv_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace phxkv {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_phxkv_2eproto();
void protobuf_AssignDesc_phxkv_2eproto();
void protobuf_ShutdownFile_phxkv_2eproto();

class KVData;
class KVOperator;
class KVResponse;

// ===================================================================

class KVOperator : public ::google::protobuf::Message {
 public:
  KVOperator();
  virtual ~KVOperator();

  KVOperator(const KVOperator& from);

  inline KVOperator& operator=(const KVOperator& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KVOperator& default_instance();

  void Swap(KVOperator* other);

  // implements Message ----------------------------------------------

  inline KVOperator* New() const { return New(NULL); }

  KVOperator* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KVOperator& from);
  void MergeFrom(const KVOperator& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KVOperator* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // optional bytes value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // optional uint64 version = 3;
  void clear_version();
  static const int kVersionFieldNumber = 3;
  ::google::protobuf::uint64 version() const;
  void set_version(::google::protobuf::uint64 value);

  // optional uint32 operator = 4;
  void clear_operator_();
  static const int kOperatorFieldNumber = 4;
  ::google::protobuf::uint32 operator_() const;
  void set_operator_(::google::protobuf::uint32 value);

  // optional uint32 sid = 5;
  void clear_sid();
  static const int kSidFieldNumber = 5;
  ::google::protobuf::uint32 sid() const;
  void set_sid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:phxkv.KVOperator)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::uint64 version_;
  ::google::protobuf::uint32 operator__;
  ::google::protobuf::uint32 sid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_phxkv_2eproto();
  friend void protobuf_AssignDesc_phxkv_2eproto();
  friend void protobuf_ShutdownFile_phxkv_2eproto();

  void InitAsDefaultInstance();
  static KVOperator* default_instance_;
};
// -------------------------------------------------------------------

class KVData : public ::google::protobuf::Message {
 public:
  KVData();
  virtual ~KVData();

  KVData(const KVData& from);

  inline KVData& operator=(const KVData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KVData& default_instance();

  void Swap(KVData* other);

  // implements Message ----------------------------------------------

  inline KVData* New() const { return New(NULL); }

  KVData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KVData& from);
  void MergeFrom(const KVData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KVData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // optional uint64 version = 2;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::uint64 version() const;
  void set_version(::google::protobuf::uint64 value);

  // optional bool isdeleted = 3;
  void clear_isdeleted();
  static const int kIsdeletedFieldNumber = 3;
  bool isdeleted() const;
  void set_isdeleted(bool value);

  // @@protoc_insertion_point(class_scope:phxkv.KVData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::uint64 version_;
  bool isdeleted_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_phxkv_2eproto();
  friend void protobuf_AssignDesc_phxkv_2eproto();
  friend void protobuf_ShutdownFile_phxkv_2eproto();

  void InitAsDefaultInstance();
  static KVData* default_instance_;
};
// -------------------------------------------------------------------

class KVResponse : public ::google::protobuf::Message {
 public:
  KVResponse();
  virtual ~KVResponse();

  KVResponse(const KVResponse& from);

  inline KVResponse& operator=(const KVResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KVResponse& default_instance();

  void Swap(KVResponse* other);

  // implements Message ----------------------------------------------

  inline KVResponse* New() const { return New(NULL); }

  KVResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KVResponse& from);
  void MergeFrom(const KVResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KVResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .phxkv.KVData data = 1;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::phxkv::KVData& data() const;
  ::phxkv::KVData* mutable_data();
  ::phxkv::KVData* release_data();
  void set_allocated_data(::phxkv::KVData* data);

  // optional int32 ret = 2;
  void clear_ret();
  static const int kRetFieldNumber = 2;
  ::google::protobuf::int32 ret() const;
  void set_ret(::google::protobuf::int32 value);

  // optional uint64 master_nodeid = 3;
  void clear_master_nodeid();
  static const int kMasterNodeidFieldNumber = 3;
  ::google::protobuf::uint64 master_nodeid() const;
  void set_master_nodeid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:phxkv.KVResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::phxkv::KVData* data_;
  ::google::protobuf::uint64 master_nodeid_;
  ::google::protobuf::int32 ret_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_phxkv_2eproto();
  friend void protobuf_AssignDesc_phxkv_2eproto();
  friend void protobuf_ShutdownFile_phxkv_2eproto();

  void InitAsDefaultInstance();
  static KVResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// KVOperator

// optional string key = 1;
inline void KVOperator::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KVOperator::key() const {
  // @@protoc_insertion_point(field_get:phxkv.KVOperator.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KVOperator::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxkv.KVOperator.key)
}
inline void KVOperator::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxkv.KVOperator.key)
}
inline void KVOperator::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxkv.KVOperator.key)
}
inline ::std::string* KVOperator::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:phxkv.KVOperator.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KVOperator::release_key() {
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KVOperator::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:phxkv.KVOperator.key)
}

// optional bytes value = 2;
inline void KVOperator::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KVOperator::value() const {
  // @@protoc_insertion_point(field_get:phxkv.KVOperator.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KVOperator::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxkv.KVOperator.value)
}
inline void KVOperator::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxkv.KVOperator.value)
}
inline void KVOperator::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxkv.KVOperator.value)
}
inline ::std::string* KVOperator::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:phxkv.KVOperator.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KVOperator::release_value() {
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KVOperator::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:phxkv.KVOperator.value)
}

// optional uint64 version = 3;
inline void KVOperator::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 KVOperator::version() const {
  // @@protoc_insertion_point(field_get:phxkv.KVOperator.version)
  return version_;
}
inline void KVOperator::set_version(::google::protobuf::uint64 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:phxkv.KVOperator.version)
}

// optional uint32 operator = 4;
inline void KVOperator::clear_operator_() {
  operator__ = 0u;
}
inline ::google::protobuf::uint32 KVOperator::operator_() const {
  // @@protoc_insertion_point(field_get:phxkv.KVOperator.operator)
  return operator__;
}
inline void KVOperator::set_operator_(::google::protobuf::uint32 value) {
  
  operator__ = value;
  // @@protoc_insertion_point(field_set:phxkv.KVOperator.operator)
}

// optional uint32 sid = 5;
inline void KVOperator::clear_sid() {
  sid_ = 0u;
}
inline ::google::protobuf::uint32 KVOperator::sid() const {
  // @@protoc_insertion_point(field_get:phxkv.KVOperator.sid)
  return sid_;
}
inline void KVOperator::set_sid(::google::protobuf::uint32 value) {
  
  sid_ = value;
  // @@protoc_insertion_point(field_set:phxkv.KVOperator.sid)
}

// -------------------------------------------------------------------

// KVData

// optional bytes value = 1;
inline void KVData::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& KVData::value() const {
  // @@protoc_insertion_point(field_get:phxkv.KVData.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KVData::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:phxkv.KVData.value)
}
inline void KVData::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:phxkv.KVData.value)
}
inline void KVData::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:phxkv.KVData.value)
}
inline ::std::string* KVData::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:phxkv.KVData.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* KVData::release_value() {
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void KVData::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:phxkv.KVData.value)
}

// optional uint64 version = 2;
inline void KVData::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 KVData::version() const {
  // @@protoc_insertion_point(field_get:phxkv.KVData.version)
  return version_;
}
inline void KVData::set_version(::google::protobuf::uint64 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:phxkv.KVData.version)
}

// optional bool isdeleted = 3;
inline void KVData::clear_isdeleted() {
  isdeleted_ = false;
}
inline bool KVData::isdeleted() const {
  // @@protoc_insertion_point(field_get:phxkv.KVData.isdeleted)
  return isdeleted_;
}
inline void KVData::set_isdeleted(bool value) {
  
  isdeleted_ = value;
  // @@protoc_insertion_point(field_set:phxkv.KVData.isdeleted)
}

// -------------------------------------------------------------------

// KVResponse

// optional .phxkv.KVData data = 1;
inline bool KVResponse::has_data() const {
  return !_is_default_instance_ && data_ != NULL;
}
inline void KVResponse::clear_data() {
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}
inline const ::phxkv::KVData& KVResponse::data() const {
  // @@protoc_insertion_point(field_get:phxkv.KVResponse.data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
inline ::phxkv::KVData* KVResponse::mutable_data() {
  
  if (data_ == NULL) {
    data_ = new ::phxkv::KVData;
  }
  // @@protoc_insertion_point(field_mutable:phxkv.KVResponse.data)
  return data_;
}
inline ::phxkv::KVData* KVResponse::release_data() {
  
  ::phxkv::KVData* temp = data_;
  data_ = NULL;
  return temp;
}
inline void KVResponse::set_allocated_data(::phxkv::KVData* data) {
  delete data_;
  data_ = data;
  if (data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:phxkv.KVResponse.data)
}

// optional int32 ret = 2;
inline void KVResponse::clear_ret() {
  ret_ = 0;
}
inline ::google::protobuf::int32 KVResponse::ret() const {
  // @@protoc_insertion_point(field_get:phxkv.KVResponse.ret)
  return ret_;
}
inline void KVResponse::set_ret(::google::protobuf::int32 value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:phxkv.KVResponse.ret)
}

// optional uint64 master_nodeid = 3;
inline void KVResponse::clear_master_nodeid() {
  master_nodeid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 KVResponse::master_nodeid() const {
  // @@protoc_insertion_point(field_get:phxkv.KVResponse.master_nodeid)
  return master_nodeid_;
}
inline void KVResponse::set_master_nodeid(::google::protobuf::uint64 value) {
  
  master_nodeid_ = value;
  // @@protoc_insertion_point(field_set:phxkv.KVResponse.master_nodeid)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace phxkv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_phxkv_2eproto__INCLUDED
