// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: phxkv.proto

#include "phxkv.pb.h"
#include "phxkv.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace phxkv {

static const char* PhxKVServer_method_names[] = {
  "/phxkv.PhxKVServer/Put",
  "/phxkv.PhxKVServer/GetLocal",
  "/phxkv.PhxKVServer/GetGlobal",
  "/phxkv.PhxKVServer/Delete",
};

std::unique_ptr< PhxKVServer::Stub> PhxKVServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< PhxKVServer::Stub> stub(new PhxKVServer::Stub(channel));
  return stub;
}

PhxKVServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Put_(PhxKVServer_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetLocal_(PhxKVServer_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetGlobal_(PhxKVServer_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(PhxKVServer_method_names[3], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PhxKVServer::Stub::Put(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::phxkv::KVResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Put_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>* PhxKVServer::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>(channel_.get(), cq, rpcmethod_Put_, context, request);
}

::grpc::Status PhxKVServer::Stub::GetLocal(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::phxkv::KVResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetLocal_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>* PhxKVServer::Stub::AsyncGetLocalRaw(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>(channel_.get(), cq, rpcmethod_GetLocal_, context, request);
}

::grpc::Status PhxKVServer::Stub::GetGlobal(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::phxkv::KVResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_GetGlobal_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>* PhxKVServer::Stub::AsyncGetGlobalRaw(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>(channel_.get(), cq, rpcmethod_GetGlobal_, context, request);
}

::grpc::Status PhxKVServer::Stub::Delete(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::phxkv::KVResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Delete_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>* PhxKVServer::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::phxkv::KVOperator& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::phxkv::KVResponse>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

PhxKVServer::Service::Service() {
  (void)PhxKVServer_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      PhxKVServer_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PhxKVServer::Service, ::phxkv::KVOperator, ::phxkv::KVResponse>(
          std::mem_fn(&PhxKVServer::Service::Put), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      PhxKVServer_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PhxKVServer::Service, ::phxkv::KVOperator, ::phxkv::KVResponse>(
          std::mem_fn(&PhxKVServer::Service::GetLocal), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      PhxKVServer_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PhxKVServer::Service, ::phxkv::KVOperator, ::phxkv::KVResponse>(
          std::mem_fn(&PhxKVServer::Service::GetGlobal), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      PhxKVServer_method_names[3],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PhxKVServer::Service, ::phxkv::KVOperator, ::phxkv::KVResponse>(
          std::mem_fn(&PhxKVServer::Service::Delete), this)));
}

PhxKVServer::Service::~Service() {
}

::grpc::Status PhxKVServer::Service::Put(::grpc::ServerContext* context, const ::phxkv::KVOperator* request, ::phxkv::KVResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhxKVServer::Service::GetLocal(::grpc::ServerContext* context, const ::phxkv::KVOperator* request, ::phxkv::KVResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhxKVServer::Service::GetGlobal(::grpc::ServerContext* context, const ::phxkv::KVOperator* request, ::phxkv::KVResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PhxKVServer::Service::Delete(::grpc::ServerContext* context, const ::phxkv::KVOperator* request, ::phxkv::KVResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace phxkv

