// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master_sm.proto

#ifndef PROTOBUF_master_5fsm_2eproto__INCLUDED
#define PROTOBUF_master_5fsm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace phxpaxos {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_master_5fsm_2eproto();
void protobuf_AssignDesc_master_5fsm_2eproto();
void protobuf_ShutdownFile_master_5fsm_2eproto();

class MasterOperator;

// ===================================================================

class MasterOperator : public ::google::protobuf::Message {
 public:
  MasterOperator();
  virtual ~MasterOperator();

  MasterOperator(const MasterOperator& from);

  inline MasterOperator& operator=(const MasterOperator& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MasterOperator& default_instance();

  void Swap(MasterOperator* other);

  // implements Message ----------------------------------------------

  inline MasterOperator* New() const { return New(NULL); }

  MasterOperator* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MasterOperator& from);
  void MergeFrom(const MasterOperator& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MasterOperator* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 nodeid = 1;
  bool has_nodeid() const;
  void clear_nodeid();
  static const int kNodeidFieldNumber = 1;
  ::google::protobuf::uint64 nodeid() const;
  void set_nodeid(::google::protobuf::uint64 value);

  // required uint64 version = 2;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::uint64 version() const;
  void set_version(::google::protobuf::uint64 value);

  // required int32 timeout = 3;
  bool has_timeout() const;
  void clear_timeout();
  static const int kTimeoutFieldNumber = 3;
  ::google::protobuf::int32 timeout() const;
  void set_timeout(::google::protobuf::int32 value);

  // required uint32 operator = 4;
  bool has_operator_() const;
  void clear_operator_();
  static const int kOperatorFieldNumber = 4;
  ::google::protobuf::uint32 operator_() const;
  void set_operator_(::google::protobuf::uint32 value);

  // required uint32 sid = 5;
  bool has_sid() const;
  void clear_sid();
  static const int kSidFieldNumber = 5;
  ::google::protobuf::uint32 sid() const;
  void set_sid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:phxpaxos.MasterOperator)
 private:
  inline void set_has_nodeid();
  inline void clear_has_nodeid();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_timeout();
  inline void clear_has_timeout();
  inline void set_has_operator_();
  inline void clear_has_operator_();
  inline void set_has_sid();
  inline void clear_has_sid();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 nodeid_;
  ::google::protobuf::uint64 version_;
  ::google::protobuf::int32 timeout_;
  ::google::protobuf::uint32 operator__;
  ::google::protobuf::uint32 sid_;
  friend void  protobuf_AddDesc_master_5fsm_2eproto();
  friend void protobuf_AssignDesc_master_5fsm_2eproto();
  friend void protobuf_ShutdownFile_master_5fsm_2eproto();

  void InitAsDefaultInstance();
  static MasterOperator* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MasterOperator

// required uint64 nodeid = 1;
inline bool MasterOperator::has_nodeid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MasterOperator::set_has_nodeid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MasterOperator::clear_has_nodeid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MasterOperator::clear_nodeid() {
  nodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_nodeid();
}
inline ::google::protobuf::uint64 MasterOperator::nodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.nodeid)
  return nodeid_;
}
inline void MasterOperator::set_nodeid(::google::protobuf::uint64 value) {
  set_has_nodeid();
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.nodeid)
}

// required uint64 version = 2;
inline bool MasterOperator::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MasterOperator::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MasterOperator::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MasterOperator::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
  clear_has_version();
}
inline ::google::protobuf::uint64 MasterOperator::version() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.version)
  return version_;
}
inline void MasterOperator::set_version(::google::protobuf::uint64 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.version)
}

// required int32 timeout = 3;
inline bool MasterOperator::has_timeout() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MasterOperator::set_has_timeout() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MasterOperator::clear_has_timeout() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MasterOperator::clear_timeout() {
  timeout_ = 0;
  clear_has_timeout();
}
inline ::google::protobuf::int32 MasterOperator::timeout() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.timeout)
  return timeout_;
}
inline void MasterOperator::set_timeout(::google::protobuf::int32 value) {
  set_has_timeout();
  timeout_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.timeout)
}

// required uint32 operator = 4;
inline bool MasterOperator::has_operator_() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MasterOperator::set_has_operator_() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MasterOperator::clear_has_operator_() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MasterOperator::clear_operator_() {
  operator__ = 0u;
  clear_has_operator_();
}
inline ::google::protobuf::uint32 MasterOperator::operator_() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.operator)
  return operator__;
}
inline void MasterOperator::set_operator_(::google::protobuf::uint32 value) {
  set_has_operator_();
  operator__ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.operator)
}

// required uint32 sid = 5;
inline bool MasterOperator::has_sid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MasterOperator::set_has_sid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MasterOperator::clear_has_sid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MasterOperator::clear_sid() {
  sid_ = 0u;
  clear_has_sid();
}
inline ::google::protobuf::uint32 MasterOperator::sid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.sid)
  return sid_;
}
inline void MasterOperator::set_sid(::google::protobuf::uint32 value) {
  set_has_sid();
  sid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.sid)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace phxpaxos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_master_5fsm_2eproto__INCLUDED
